name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
      

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: munnasingh99/made-template
          path: app

      - name: Running Pipeline
        id: pipeline_feedback
        working-directory: ./app/project
        run: |
          bash ./pipeline.sh

      - name: Testing Pipeline
        id: test_feedback
        working-directory: ./app/project
        run: |
          bash ./tests.sh

      
