name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  project-feedback:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: python -m pip install requests
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: munnasingh99/made-template
          path: app

      - name: Running Pipeline
        id: pipeline_feedback
        working-directory: ./app/project
        run: |
          bash ./pipeline.sh

      - name: Testing Pipeline
        id: test_feedback
        working-directory: ./app/project
        run: |
          bash ./tests.sh

      - name: Feedback
        id: feedback
        run: |
          echo "Testing completed successfully!. And CI Pipeline is working fine :)"

      
