name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  exercise-feedback:
    runs-on: ubuntu-latest
    steps:
      
      # Install python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Run project feeback to test
      - name: Project Feedback
        id: project_feedback
        run: |
          ./project/tests.sh

      
